#+EXPORT_FILE_NAME: ../../episodes/introduction.md
#+OPTIONS: toc:nil author:nil date:nil num:nil title:nil
#+MACRO: mdheader @@markdown:$1@@

#+begin_export markdown
---
title: "Using Markdown"
teaching: 10
exercises: 2
---
#+end_export

#+begin_questions
- How do you write a lesson using Markdown and ={sandpaper}=?
#+end_questions

#+begin_objectives
- Explain how to use markdown with The Carpentries Workbench
- Demonstrate how to include pieces of code, figures, and nested challenge blocks
#+end_objectives

** Introduction

This is a lesson created via The Carpentries Workbench. It is written in [[https://pandoc.org/MANUAL.html][Pandoc-flavored Markdown]] for static files and [r-markdown] for dynamic files that can render code into output. Please refer to the [[https://carpentries.github.io/sandpaper-docs/][Introduction to The Carpentries Workbench]] for full documentation.

What you need to know is that there are three sections required for a valid Carpentries lesson:

1. =questions= are displayed at the beginning of the episode to prime the learner for the content.
2. =objectives= are the learning objectives for an episode displayed with the questions.
3. =keypoints= are displayed at the end of the episode to reinforce the objectives.

#+begin_instructor
Inline instructor notes can help inform instructors of timing challenges associated with the lessons. They appear in the "Instructor View"
#+end_instructor

#+begin_challenge
{{{mdheader(## Challenge 1: Can you do it?)}}}

What is the output of this command?

#+begin_src r
paste("This", "new", "lesson", "looks", "good")
#+end_src

#+begin_solution
{{{mdheader(## Output)}}}

#+begin_example
[1] "This new lesson looks good"
#+end_example
#+end_solution
#+end_challenge

#+begin_challenge
{{{mdheader(## Challenge 2: how do you nest solutions within challenge blocks?)}}}

#+begin_solution
You can add a line with at least three colons and a =solution= tag.
#+end_solution
#+end_challenge

** Figures

You can use standard markdown for static figures with the following syntax:

~![optional caption that appears below the figure](figure url){alt='alt text for accessibility purposes'}~

[[https://raw.githubusercontent.com/carpentries/logo/master/Badge_Carpentries.svg][You belong in The Carpentries!{alt='Blue Carpentries hex person logo with no text.'}]]

#+begin_callout
Callout sections can highlight information.

They are sometimes used to emphasise particularly important points but are also used in some lessons to present "asides": content that is not central to the narrative of the lesson, e.g. by providing the answer to a commonly-asked question.
#+end_callout

** Math

One of our episodes contains $\LaTeX$ equations when describing how to create dynamic reports with {knitr}, so we now use mathjax to describe this:

~$\alpha = \dfrac{1}{(1 - \beta)^2}$~ becomes: $\alpha = \dfrac{1}{(1 - \beta)^2}$

Cool, right?

#+begin_keypoints
- Use =.md= files for episodes when you want static content
- Use =.Rmd= files for episodes when you need to generate output
- Run =sandpaper::check_lesson()= to identify any issues with your lesson
- Run =sandpaper::build_lesson()= to preview your lesson locally
#+end_keypoints

#+begin_export markdown
[r-markdown]: https://rmarkdown.rstudio.com/
#+end_export
